name: Release

on: workflow_dispatch

jobs:
  release:
    name: Run Gradle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Build, release then publish assets
        run: |
          ./gradlew -i -S fullRelease \
            -Pgithub.token=${{ secrets.GITHUB_TOKEN }} \
            -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} \
            -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}